MACHINE_TYPE="n1-standard-8"
NP_ACCELERATOR_TYPE="nvidia-tesla-p100"
NP_ACCELERATOR_COUNT="1"

USE_NFS_PVS=false
DYNAMIC_NFSCP_DEPLOYMENT=false
NFSSP_PERSISTENCE_ENABLED=true
GKE_DEPLOYMENT=true

APPSTORE_DJANGO_SETTINGS="scidas"