kind: Service
apiVersion: v1
metadata:
  name: {{ include "roger.fullname" . }}-airflow-ui-svc
  labels:
    app: airflow
    component: web
    release: {{ .Release.Name }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: {{ .Values.web.ambassador.airflowUI.map_name }}
      prefix: {{ .Values.web.ambassador.airflowUI.prefix }}
      service: {{ include "roger.fullname" . }}-airflow-ui-svc:8080
      rewrite: {{ .Values.web.ambassador.airflowUI.rewrite }}

spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: airflow
    component: web
    release: {{ .Release.Name }}
  type: ClusterIP

