---
# service account for running pod-reaper
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reaper-service-account
  namespace: {{.Release.Namespace}}

---
# minimal permissions required for running pod-reaper at cluster level
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reaper-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
- apiGroups:
  - "apps"
  resources:
    - deployments
    - deployments/scale
    - replicasets
    - replicasets/scale
  verbs:
    - delete
    - get
    - list
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
    - deployments
    - deployments/scale
    - replicasets
    - replicasets/scale
  verbs:
    - delete
    - get
    - list

---
# binding the above cluster role (permissions) to the above service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reaper-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reaper-role
subjects:
- kind: ServiceAccount
  name: pod-reaper-service-account
  namespace: {{.Release.Namespace}}
