# Default values for nfsrods.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: irods/nfsrods
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 1.0.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  nfsPort: 2049
  mountdPort: 20048
  rpcbindPort: 111
  # -- NOTE: This IP must be a valid, unused IP in the cluster's serviceCIDR
  ip: 10.233.58.200

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

runArgs: "/usr/sbin/useradd -m -u 1000 -s /bin/bash rods; ./start.sh"

sharedStorage:
  createPVC: true
  createPV: true
  # -- No data is actually stored here, just a pointer to the nfsrods service IP.
  storageSize: 100Gi
  # -- This storageClass doesn't need to exist in the cluster since the PVC is directly selecting the PV
  storageClass: nfsrods-sc
  nfs:
    path: /

server:
  nfs_server:
    port: 2049
    irods_mount_point: /ExampleZone
    user_information_refresh_time_in_milliseconds: 3600000
    file_information_refresh_time_in_milliseconds: 1000
    user_access_refresh_time_in_milliseconds: 1000
  irods_client:
    zone: ExampleZone
    host: example.com
    port: 1247
    default_resource: rootResc
    ssl_negotiation_policy: CS_NEG_REFUSE
    proxy_admin_account:
      username: user
      password: password

global:
  stdnfsPvc: stdnfs
