apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.web.db.name }}
  name: {{ .Values.web.db.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.web.db.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Values.web.db.name }}
    spec:
      containers:
      - image: hydroshare/hs_postgres:9.4.7
        name: {{ .Values.web.db.name }}
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgis-claim0
      restartPolicy: Always
      volumes:
      - name: postgis-claim0
        persistentVolumeClaim:
          claimName: postgis-claim0
status: {}
