apiVersion: v1
kind: Service
metadata:
  annotations: 
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.web.tool.name }}
  name: {{ .Values.web.tool.name }}
spec:
  ports:
  - port: 8983
    targetPort: 8983
  selector:
    io.kompose.service: {{ .Values.web.tool.name }}
status:
  loadBalancer: {}
