apiVersion: v1
kind: Service
metadata:
  name: nginx-revproxy
  namespace: braini
spec:
  type: LoadBalancer
  #loadBalancerIP: {{ .Values.service.IP }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-revproxy
