{{ if .Values.basicAuthCreds }}
# Used to protect kubecost, prometheus, and alertmanager which don't natively support auth.
apiVersion: v1
kind: Secret
metadata:
  name: "monitoring-basicauth"
data:
  auth: "{{ .Values.basicAuthCreds | b64enc }}"
{{- end }}
