apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  namespace: braini
  labels:
    app: {{ .Values.db.name }}
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: {{ .Values.db.name }}
