apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    service: {{ template "tycho-api.name" . }}
  name: {{ template "tycho-api.name" . }}
  namespace: braini
spec:
  type: LoadBalancer
  selector:
    app: {{ template "tycho-api.name" . }}
  ports:
  - name: http
    port: 8099
    protocol: TCP
    targetPort: 8099
