pipeline {
  agent {
    kubernetes {
        label 'kaniko-build-agent'
        yaml """
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: jnlp
    workingDir: /tmp/jenkins
  - name: kaniko
    workingDir: /tmp/jenkins
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: jenkins-docker-cfg
      mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: rencibuild-imagepull-secret
          items:
            - key: .dockerconfigjson
              path: config.json
"""
        }
    }
    stages {
        stage('Build') {
            environment {
                PATH = "/busybox:/kaniko:$PATH"
                DOCKERHUB_CREDS = credentials("${env.REGISTRY_CREDS_ID_STR}")
                DOCKER_REGISTRY = "${env.DOCKER_REGISTRY}"
            }
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    sh '''#!/busybox/sh
                        /kaniko/executor --dockerfile ./nginx/Dockerfile \
                                         --context ./nginx/ \
                                         --verbosity debug \
                                         --no-push \
                                         --destination helxplatform/nginx:1.0.24 \
                                         --destination helxplatform/nginx:latest \
                                         --tarPath image.tar
                        '''
                }
            }
            post {
                always {
                    archiveArtifacts artifacts: 'image.tar', onlyIfSuccessful: true
                }
            }
        }
        //stage('Test') {
        //    steps {
        //        container('agent-docker') {
        //            sh '''
        //            echo test
        //            '''
        //        }
        //    }
        //}
        stage('Publish') {
            steps {
                container('agent-docker') {
                    sh '''
                    echo "Publish stage"
                    crane auth -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW $DOCKER_REGISTRY
                    crane push image.tar helxplatform/nginx:1.0.24
                    crane push image.tar helxplatform/nginx:latest
                    '''
                }
            }
        }
    }
}