apiVersion: v1
kind: Service
metadata:
  name: {{ include "appstore.fullname" . }}
  labels:
    {{- include "appstore.labels" . | nindent 4 }}
  {{- if .Values.ambassador.flag }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  appstore-mapping
      prefix: /
      service: {{ include "appstore.fullname" . }}:8000
      timeout_ms: 300000
      idle_timeout_ms: 500000
      connect_timeout_ms: 500000

  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.name }}
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    {{- include "appstore.selectorLabels" . | nindent 6 }}
