using System.ComponentModel;

namespace Renci.ReCCAP.Dashboard.Web.Models.Enums
{
    /// <summary>
    ///
    /// </summary>
    public enum ReportParameterDataType
    {
        /// <summary>
        /// The text
        /// </summary>
        [Description("Text")]
        Text = 1,

        /// <summary>
        /// The number
        /// </summary>
        [Description("Number")]
        Number = 2,

        /// <summary>
        /// The regex
        /// </summary>
        [Description("Regular Expression")]
        Regex = 3,

        /// <summary>
        /// The date
        /// </summary>
        [Description("Date")]
        Date = 5,

        /// <summary>
        /// The types list
        /// </summary>
        [Description("Types List")]
        TypesList = 10,

        /// <summary>
        /// The list
        /// </summary>
        [Description("URL List")]
        UrlList = 11,

        /// <summary>
        /// The list
        /// </summary>
        [Description("Custom List")]
        CustomList = 12,

        /// <summary>
        /// The list generated by executing SQL.
        /// </summary>
        [Description("SQL List")]
        SqlList = 13
    }
}