{{ if .Values.redis.dumpUri }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{- include "search.fullname"  . }}-seed-db-job"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{- include "search.fullname"  . }}-seed-db-job"
    spec:
      restartPolicy: Never
      containers:
        - name: init-db
          image: busybox
          command:
            - "wget"
          args:
            - "{{ .Values.redis.dumpUri }}"
            - "-O"
            - "/data/dump.rdb"
          volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
        - name: "redis-data"
          persistentVolumeClaim:
            claimName: {{ include "search.redis.tplValue" (dict "value" .Values.redis.persistence.existingClaim "context" $) }}
{{- end }}