replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

app:
  name: tycho-api

serviceAccount:
  create: true
  name: tycho-api

service:
  type: ClusterIP
  port: 80

resources:
  limits:
     cpu: 100m
     memory: 128Mi
  requests:
     cpu: 100m
     memory: 128Mi
