apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
# See https://www.getambassador.io/docs/latest/topics/running/ambassador/
# Use ambassador_id only if you are using multiple ambassadors in the same cluster.
# See below for more information.
  ambassador_id: "{{ .Values.global.ambassador_id }}"
